### ISSUE TITLE
请问collectd-client这个包是做什么的?没有搜到相关资料,maven也没下载下来

### ISSUE THREAD

**Issue by mrdear** [hawkingrei/bitcoin-collectd#1]
<dependency>
            <groupId>io.socket</groupId>
            <artifactId>collectd-client</artifactId>
            <version>${socket.io-client.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.gson</groupId>
                    <artifactId>gson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by hawkingrei** [comment]
这是一个socketio客户端，官方版本只支持v1.x 后版本，但是huobi的websocket是在0.x版本，于是在网上找了一个socketio 0.x版本客户端，但是其代码质量才差，就自己搞了一份

**Comment by hawkingrei** [comment]
他的包是在https://github.com/hawkingrei/maven-repo 下，源代码在      https://github.com/hawkingrei/socket.io-java-client

**Comment by mrdear** [comment]
@hawkingrei  soga,之前的版本确实很老了,都几年没更新了,回去接着看
